POST http://localhost:3001/users/add HTTP/1.1
content-type: application/json

{
    "username": "timmy tommy"
}

GET http://localhost:3001/users
Content-Type: application/json

DELETE http://localhost:3001/users/delete/5f790ddb4593aa467c086199
Content-Type: application/json
